### PR TITLE
Add optional dark theme

### PR DESCRIPTION
**Pull request by vitaly-zdanevich**
Save our eyes. And batteries.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

image

### CODE REVIEW

**Comment by behdad** [comment]
Thanks...

I'm pretty sure that style file is produced by gtk-doc when we build the docs, so it be rewritten with the next release.

We need a better fix that should go into https://github.com/harfbuzz/harfbuzz/tree/master/docs but I don't know how exactly.

**Comment by vitaly-zdanevich** [comment]
Maybe you know who to ask?

**Comment by behdad** [comment]
I was hoping that they would speak up. @khaledhosny @n8willis

**Comment by khaledhosny** [comment]
I wouldn’t know either. I don‘t think GTK-Doc has support for CSS customizations.

**Comment by behdad** [comment]
We can have our own additional style.css and append it to the end of the gtk-doc-created one. Either at make time in doc/, or at CI deploy time.

**Comment by vitaly-zdanevich** [comment]
Maybe I need to do a Pull Request here? https://github.com/GNOME/gtk-doc/blob/master/style/style.css

**Comment by behdad** [comment]
> Maybe I need to do a Pull Request here? https://github.com/GNOME/gtk-doc/blob/master/style/style.css

Yes, that would be best I guess. Thanks!

**Comment by vitaly-zdanevich** [comment]
Created https://gitlab.gnome.org/GNOME/gtk-doc/-/merge_requests/64

**Comment by behdad** [comment]
Thanks.

**Pull request closed without merging**
